import Header from "./components/header/header";
import "./globals.css";
import { Inconsolata } from "next/font/google";

const font = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="page-container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
