CREATE TABLE category_rows (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id int,
    name varchar NOT NULL,
    jan numeric(12, 2),
    feb numeric(12, 2),
    mar numeric(12, 2),
    apr numeric(12, 2),
    may numeric(12, 2),
    jun numeric(12, 2),
    jul numeric(12, 2),
    aug numeric(12, 2),
    sep numeric(12, 2),
    oct numeric(12, 2),
    nov numeric(12, 2),
    dec numeric(12, 2),
    CONSTRAINT fk_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);