CREATE TABLE entries (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id int,
    description varchar NOT NULL,
    date date NOT NULL,
    amount numeric(12, 2) NOT NULL,
    CONSTRAINT fk_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);