CREATE TABLE accounts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id int NOT NULL,
    name VARCHAR NOT NULL,
    CONSTRAINT fk_category FOREIGN KEY(category_id) REFERENCES categories(id)
);